xgboost:
  params:
    max_depth: 5
    eta: 0.5
    alpha: 2.5
    objective: "binary:logistic"
    eval_metric: "auc"
    subsample: 0.8
    colsample_bytree: 0.8
    min_child_weight: 3
    tree_method: "auto"
    predictor: "auto"
  training:
    num_boost_round: 150
    early_stopping_rounds: 10
    verbose_eval: 10
  cv:
    nfold: 3
    stratified: true
    shuffle: true
    seed: 42

model_registry:
  save_path: "models"
  model_name: "xgboost_model"
  version: "v1"
  metadata:
    description: "XGBoost model for bank marketing prediction"
    target_metric: "auc"
    threshold: 0.75

inference:
  batch_size: 1000
  prediction_threshold: 0.5
