version: '3.8'

services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
    command: run

  test:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
    command: test

  monitor:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    command: monitor

  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    ports:
      - "8888:8888"  # For Jupyter notebook
    command: dev

  jupyter:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

networks:
  default:
    name: ml_pipeline_network
