version: '3.8'

services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
    command: python src/pipeline.py

  test:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python -m pytest tests/ --cov=src --cov-report=xml

  monitor:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: python src/monitoring/model_monitor.py

  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    ports:
      - "8888:8888"  # For Jupyter notebook
    command: /bin/bash

  jupyter:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

networks:
  default:
    name: bank_marketing_network
